### ISSUE TITLE
Multiple FadeCandy's

### ISSUE THREAD

**Issue by ImanolGo** [DHaylock/ofxOPC#1]
Hi,

Have you tried the multiple FadeCandy's with the ofxOPC class?

I've tried this:

uint16_t data_length = NUMBER_OF_FADECANDYS \* 8 \* 64 \* sizeof(OPCPacket_SPCData_t);

And offset as:

uint16_t channel_offset = (fadeCandyIndex-1)_8_64  + (channel - 1) \* 64;

But always got 

"Unsupported OPC command: nnn"

Do you have any clue or have experience with several FadeCandys?

Imanol

**Comment by DHaylock** [comment]
Hi @ImanolGo,

I haven't tried unfortunately.

This may be wrong but, you could work around multiple units by creating two fcservers changing the port address. Then in the oF app create two ofxOPC objects assign them with different port numbers then pass the color information out that way.

I know that you can assign the units start address. So the first unit starts at 0 to 512, then you can set the second unit to start at 513 to 1024. All you would do is increase the length of Channels x 2. 

Its line 24 of ofOPC.cpp from

uint16_t data_length = 8 \* 64 \* sizeof(OPCPacket_SPCData_t);

to

 uint16_t data_length = 16 \* 64 \* sizeof(OPCPacket_SPCData_t);

I'll have a look round see what i can do.

Best

**Comment by DHaylock** [comment]
https://github.com/scanlime/fadecandy/blob/master/doc/fc_server_config.md

This might help

**Comment by ImanolGo** [comment]
Hi @DHaylock 

I finally left 

uint16_t data_length = 8 \* 64 \* sizeof(OPCPacket_SPCData_t);

But had a signed a different OPC channel for each FadeCandy.

OPC_SPC_packet->header.channel = channel;

Then on the server side I configured it like,

{
    "listen": [ "127.0.0.1", 7890 ],
    "verbose": true,
    "color": { "gamma": 2.5, "whitepoint": [ 1, 1, 1 ] },
    "devices": [
        {
            "type": "fadecandy",
            "serial": "XXXXXXXX1",
            "map": [ [ 1, 0, 0, 512 ] ]
        },
        {
            "type": "fadecandy",
            "serial": "XXXXXXXX2",
            "map": [ [ 2, 0, 0, 512 ] ]
        }
    ]
}

And "voila", that worked perfectly for me. 

Theoretically that should work for up to 256 different Fadecandys, which a fairly big amount of them.

Thanks,

Imanol

**Comment by DHaylock** [comment]
Thats fantastic, I know its a bit cheeky but would be interested to see what you do with it? I'll add to the readme later this week

**Comment by ImanolGo** [comment]
Sure, no problem.

It will be a light sculpture made with 11 fadecandys and 85 independent neopixel rings. Unfortunately, it's not built yet. I'm just implementing the software and testing the prototype.

**Comment by ImanolGo** [comment]
If you are curious, here is the full software that I implemented:

https://github.com/ImanolGo/HaloLight
