### ISSUE TITLE
All strips not working on oF 0.9.0

### ISSUE THREAD

**Issue by emmanuelgeoffray** [DHaylock/ofxOPC#3]
Hey there,
Thanks for the great addon I'm testing right now.
The rings works good, and I love the effects you've made for testing. Congrats!

However, I have a led strip in my hand, not a ring :)
So I tried 
- SingleStick
- Strip60px
- multipleStrips

and none of them works.
On the rendering in the top left corner, it doesn't get any colors.
See image attached.
![screenshot from 2016-02-02 12 07 12](https://cloud.githubusercontent.com/assets/808090/12747676/ae39f30a-c9a5-11e5-8561-3b28118adc4a.png)

My version of oF is 0.9.0, did someone else tested with this version?

Thanks,
Emmanuel

**Comment by DHaylock** [comment]
Hi @emmanuelgeoffray 

No worries,

I hadn't tried it with 0.9.0, but I've got a load of errors going on OSX.

I'll have a look now :)

Best

**Comment by DHaylock** [comment]
Ok there are some really strange things going on here, I'll push a new version once i've fixed these issues

Thank for alerting me 

Best

**Comment by DHaylock** [comment]
Hi @emmanuelgeoffray,

I've rewritten the addon should be far more stable and all classes should work. 
You might have to rework some of the code. 

For example the Neopixel objects do not grab the image beneath any more. They grab pixels from a main stage element, just draw into the stage :).

See the examples

Best

**Comment by emmanuelgeoffray** [comment]
thanks!
