### ISSUE TITLE
M_PI undeclared

### ISSUE THREAD

**Issue by bduhan** [DHaylock/ofxOPC#5]
Great project, thank you!

In Visual Studio Community Edition 2015 I get multiple errors stating that `M_PI` is undeclared in [ofxNeoPixelRing.cpp](https://github.com/DHaylock/ofxOPC/blob/master/src/ofxNeoPixelRing.cpp).  Everything works if I directly include `math.h` like this:

```cpp
#define _USE_MATH_DEFINES
#include <math.h>
```

I did not submit a pull request because this has not been tested on Linux and OSX yet and it probably makes more sense to change this elsewhere.

**Comment by DHaylock** [comment]
Hi @bduhan,

I've added the maths header works fine with linux and OSX.

Cheers for spotting this.

D
